### ISSUE TITLE
Mod reference tagging system

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#146]
I'm running into an issue as I am processing flair apps. Trades are no longer marked as "Approved" when edited, which put them in the same status as those that were _specifically_ not approved for flair. That means I have to manually check every unapproved trade again.

Could we mark a trade as "rule breaking" or "not counting towards flair" so we know not to check it again, even if it is edited?

**Comment by YaManicKill** [comment]
Renamed to better reflect the solution

**Comment by not-an-aardvark** [comment]
I was thinking we could have it work like reddit comments do. A mod can remove a trade, which causes it to be visible to mods and to the user that created it, but invisible to everyone else. Then the mod can tell the user to fix something, and if it gets fixed the mod can approve it as normal, which makes it visible to everyone again.

**Comment by YaManicKill** [comment]
See, I was literally just thinking tags that the mods put on it, that only we can see. Yours seems a little overly complex tbh. And the tagging system can solve multiple things.

**Comment by TheSonAlsoRises** [comment]
Duplicate, closing in favor of #615.
