### ISSUE TITLE
Sorting search results by date?

### ISSUE THREAD

**Issue by blackaurora** [pokemontrades/flairhq#231]
Since the value of things change over time, I think it'd be useful to be able to search for things in order of date. Pretty sure this would have to be done using the date submitted to FlairHQ rather than the date of the actual trade, so it wouldn't be exactly accurate, but would still be better than nothing.

**Comment by YaManicKill** [comment]
There is a possibility within this (that would have to be retroactive and so increases complexity) and that's when someone adds a trade, we try and find the date that the trade actually occurred. Possibly the easiest way to do that is find the date that the comment at the top of the tree (handily, the one we are given) however, if a trade takes several months (there have been some), then this can be a big difference. 

Here are some other options. We could go down the comment tree and find the 

* last date
* date range
* mode date
* median date 
* or we could just ask the user to enter a date

The last one is obviously not a great one as we would have thousands of trades without a date on them until people edit them. I'd say no to that one.

Date range would be confusing for people.

Last date has similar issues to first date.

Median date would be hard to define when we have a tree, and I'm not sure what use it would have.

Mode date...well, I actually quite like that one. The date that has the most number of comments is most likely to be the date the trade actually happened. There is obviously a possibility it would be the first one (say we spend a day discussing the trade but we don't actually do it till a week later) but it seems to be the least problematic.

Thoughts, guys?

**Comment by TheSonAlsoRises** [comment]
As I said on the IRC, the date of the first comment is probably the better/simpler option.

That being said, there probably are open issues on Github that have a higher priority than this.

**Comment by not-an-aardvark** [comment]
At the moment, it seems like search results are sorted by date added to FlairHQ. I suppose we could make it slightly more accurate by checking the date of the first comment in the chain, but I'm not sure it's worth making an api call every time someone adds a reference for that small benefit.

**Comment by YaManicKill** [comment]
Yeah, I think we should close this, I don't think it's worth the work and we'll never end up doing it. Any objections?

**Comment by TheSonAlsoRises** [comment]
No objections.
