### ISSUE TITLE
Involvement flair and HoK issues?

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#233]
It appears one of our users had the following flair:

>shinycharm1 hok1 hok hok1 hok

Raia fixed it.

There might be a conflict somewhere?

**Comment by YaManicKill** [comment]
Wait, what's hok?

**Comment by TheSonAlsoRises** [comment]
Honor of Kalos, a temporary flair distributed in some occasions (last minute redemptions for example).

**Comment by YaManicKill** [comment]
Aha, gotcha. Will take a look.

**Comment by not-an-aardvark** [comment]
This is fixed now since we've changed how we add on new flair.
