### ISSUE TITLE
Event trades: list of events

### ISSUE THREAD

**Issue by YaManicKill** [pokemontrades/flairhq#237]

**Comment by YaManicKill** [comment]
You know, I didn't give enough information and I can't remember what this is. I'll have to look through the feedback again to figure it out.

**Comment by TheSonAlsoRises** [comment]
It could have been a request to provide a standardized list of event Pokémon (eg SUM2013 Dialga) so you would not have to manually input it and everyone would use the same terminology.

**Comment by YaManicKill** [comment]
I'm not sure I would have added a story for that cause I think it has many problems. I like the overall idea. I'll think about it. Will check the feedback anyway to make sure that's what it is.
