### ISSUE TITLE
hq.porygon.co does not use https

### ISSUE THREAD

**Issue by not-an-aardvark** [pokemontrades/flairhq#386]
Among other things, this could allow a packet sniffer to steal confidential info such as Reddit access tokens.

I heard through the grapevine that we were considering getting an SSL certificate from somewhere -- what's the status on that?

**Comment by YaManicKill** [comment]
Well we don't ever pass reddit access tokens from the client to server or back again. They are passed only between server and reddit, which is ssl.

Anyway, yes, once I get access with the right domain, I'll be adding SSL anyway.

**Comment by not-an-aardvark** [comment]
> Well we don't ever pass reddit access tokens from the client to server or back again. They are passed only between server and reddit, which is ssl.

[Cannot confirm](https://i.imgur.com/rN5Mflj.png). We should probably fix this even when we end up getting SSL, though.

**Comment by YaManicKill** [comment]
Ah yes. But remember they can't do anything with it without our app
secrets.

**Comment by YaManicKill** [comment]
Got enabled access to lets encrypt, s owe should do this reasonably soon. Maybe not 2.3, but the version after that. We can re-prioritise once 2.2 is out the door.

https://letsencrypt.readthedocs.org/en/latest/using.html#installation-and-usage

**Comment by not-an-aardvark** [comment]
This was fixed awhile ago.
