### ISSUE TITLE
Specify 64 character limit is reddit's

### ISSUE THREAD

**Issue by NotRaia** [pokemontrades/flairhq#443]
Right now it just says "maximum is 64 characters" and we should probably specify "maximum on reddit is 64 characters" to avoid complaints.

**Comment by not-an-aardvark** [comment]
[How's this?](https://i.gyazo.com/dc52f1e535cd715d2c436ed782cd92bd.png)

**Comment by TheSonAlsoRises** [comment]
It looks fine to me.

**Comment by not-an-aardvark** [comment]
This change has been implemented for the next version, so I'm closing this issue.
