### ISSUE TITLE
Fix some client logic

### ISSUE THREAD

**Issue by not-an-aardvark** [pokemontrades/flairhq#448]
A few inefficiencies I've noticed:

* `$scope.user` is defined asynchronously, which is annoying.
* The current user's references are always retrieved when loading a page, even when the user is viewing someone else's page.
* The client sends a request to mod-only endpoints such as /flair/apps/all even when the user is not a mod.

**Comment by YaManicKill** [comment]
Are all of these done?

**Comment by not-an-aardvark** [comment]
This is fixed now.
