### ISSUE TITLE
Can't use async functions in Flairs.js and References.js

### ISSUE THREAD

**Issue by not-an-aardvark** [pokemontrades/flairhq#449]
These are the services that are `require`d by the client. Browserify throws an error when it sees async functions in these services, even if those functions aren't actually being used by the client.
```
exports.exciting_function_name = async function (param1, param2, param3) {
                                       ^^^^^^^^

SyntaxError: Unexpected token function

```

We should either (a) fix browserify if that's possible, or (b) have a separate service which specifically contains shared client functions, and keep all the async stuff in a separate file.

**Comment by YaManicKill** [comment]
This will be because apparently babelify doesn't set the level to be experimental by default (Whereas babel does by default, hence why our server-side hook works).

https://github.com/babel/babelify/tree/v6.4.0#enable-experimental-transforms

**Comment by YaManicKill** [comment]
So, it doesn't seem to be browserify. I only get an error for Flairs.js (References.js seems to work fine) and it's because we include it in a local in views.js. Remove it from there and it works fine.

**Comment by not-an-aardvark** [comment]
Are you sure? I get an error when I add `async` to the first line of References.js.

```javascript
exports.approve = async function (ref, approve) { // (Causes error)
```

**Comment by YaManicKill** [comment]
I am sure. I do not get this error after your fix from last night.
