### ISSUE TITLE
Allow apps to be 'claimed'

### ISSUE THREAD

**Issue by not-an-aardvark** [pokemontrades/flairhq#451]
In other words, have some sort of visual indicator on the flair app list when an app has been 'claimed' by a mod, to prevent two people from inadvertently working on the same app at the same time.

We discussed how the claiming would work on IRC. Something automatic would probably be best, and it should also have a way of expiring after a certain point, so that an app doesn't remain claimed if a mod forgets about it later.

I think it would be best if it worked like this:

* A user's apps become 'claimed' when a mod clicks on a link to a trade on their profile.
* The expires after a short amount of time (e.g. 5 minutes). However, this timer gets reset every time the mod clicks another link to a trade.
* While an app is claimed, any other mod who views the flair app list will see 'claimed by /u/so-and-so' next to that app.

In order to trigger the refresh when a link is clicked, I think we would have to make links to trades be redirect links. This could be unintuitive for users, so in theory we could make it so only mods see the redirects, and regular users see direct links. Alternatively, we could have regular users see redirects as well, which could be useful for 'recently viewed' history tracking, etc.

**Comment by YaManicKill** [comment]
Instead of the link being a redirect link, just watch the links being clicked and run a function that sends something back to the server. Only do it for mods, obviously, but I think that'll be much better than redirect links.

**Comment by not-an-aardvark** [comment]
Oh, that's possible? I was thinking it would require changing the links to javascript.void(0) or something like that.

**Comment by YaManicKill** [comment]
Nah, you just need to add an ng-click, and then do

vm.clickedLink = function () {
someCodeToTellServerHere;
return true;
}

I'm pretty sure that should run the code and then redirect the website to the url on the link. Note that async code won't continue, so you'll need to make sure that it sends the request to the server before redirecting, but I'm pretty sure it will, you just won't get teh response back (but obviously, you don't want to wait for the response).

**Comment by YaManicKill** [comment]
This is done, yes?

**Comment by not-an-aardvark** [comment]
Yes, it's fixed.
