### ISSUE TITLE
Show banned users on their public profile

### ISSUE THREAD

**Issue by YaManicKill** [pokemontrades/flairhq#469]
So we used to show people who were banned in fapp, but now that we ban them in reddit rather than fapp, this doesn't work

(or, possibly, if we ban them within fapp as well as reddit, then the ones who were banned before don't show)

We should probably show users banned on reddit.

**Comment by not-an-aardvark** [comment]
We already do ban them within flairhq, but the people who were banned before we started doing that are not banned on flairhq. We could run a one-time script to port all the accounts on the banlist.

**Comment by YaManicKill** [comment]
That sounds good, but we will need to make sure that everyone uses that for
banning.

**Comment by not-an-aardvark** [comment]
I ran a script to ban old reddit-banned accounts on FlairHQ, so this is fixed now.
