### ISSUE TITLE
FlairHQ occasionally causes 'unresponsive script' error in Firefox

### ISSUE THREAD

**Issue by not-an-aardvark** [pokemontrades/flairhq#497]
See [screenshot](https://i.imgur.com/vWU4X0Q.jpg). It doesn't happen every time, and apparently closing/restarting the browser fixes the issue for awhile.

**Comment by Raia** [comment]
Do we know if this still happens? @robertdyjas have you encountered this lately?

**Comment by robertdyjas** [comment]
I've never seen this. The only occurrence I've heard about was your (6I think) comment about this happening when you try to mass approve big amount of trades (not sure if this was on FF or other browser).

**Comment by Raia** [comment]
Alright, I'll close this then and we can reopen if we ever see it again.
