### ISSUE TITLE
incorrect addition when editing egg/TSV checks

### ISSUE THREAD

**Issue by dianjin** [pokemontrades/flairhq#498]
<img width="544" alt="screen shot 2015-12-29 at 3 28 02 pm" src="https://cloud.githubusercontent.com/assets/7786116/12041638/1b0c3842-ae41-11e5-9c04-3fbd8797d48e.png">

When you edit the number of eggs checked, it concatenates the strings instead of adding the numbers and displays that in the header as shown above. Problem goes away when you refresh the page.

**Comment by not-an-aardvark** [comment]
Hmm, can confirm. I'll look into fixing that.

**Comment by not-an-aardvark** [comment]
I just committed a fix, so I'm going to close this issue now. The fix isn't live yet, but it'll probably be deployed when we do a bugfix update sometime in the near future. Thanks for the report.
