### ISSUE TITLE
Limit the size of the user's introduction

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#50]
There is no limit to the number of characters in your introduction, which could lead to abuse. 2 possible fixes: limit the number of characters while typing up the intro, or truncate it on the user's page.

**Comment by YaManicKill** [comment]
Ah bugger, I do need to limit it anyway, because it bugs out if you put in too long.

**Comment by not-an-aardvark** [comment]
[I see the issue.](https://i.gyazo.com/e225fd44fd2e2808fe4dd8ccc95f7e8d.png)

In addition to limiting the size, we should also make the text wrap.

**Comment by YaManicKill** [comment]
It wraps if you actually have spaces...

**Comment by not-an-aardvark** [comment]
Ah, fair enough. Still, maybe we should make it wrap without spaces so that people can't do something like that.

What would a reasonable length limit be -- 10000 characters? That's the max length of a reddit comment, and I can't really see anyone needing to go over it.

**Comment by YaManicKill** [comment]
Yeah, sounds good.
