### ISSUE TITLE
Add a dropdown of ban reasons to the ban form

### ISSUE THREAD

**Issue by not-an-aardvark** [pokemontrades/flairhq#513]
See [here](https://www.reddit.com/r/modnews/comments/42o2i0/moderators_subreddit_rules_now_available_for_all/).

The one tricky part of this will be to fetch the items for the dropdown, since they could change on reddit and flairhq might not notice. I think there are three options:
1. Refresh the rules list whenever someone loads the ban form
2. Refresh the rules list periodically (every day, week, etc.)
3. Don't refresh the list automatically, and have some mod-only endpoint that triggers a refresh

Given that we probably won't be changing the list of rules too often once they're decided, I think option 2 or 3 would be best.

**Comment by Kirzi** [comment]
I think I'd prefer that we didn't do this. We want more specific/custom ban reasons in every scenario, so I think we can just close this.
