### ISSUE TITLE
Check if the left-pad debacle affects us

### ISSUE THREAD

**Issue by YaManicKill** [pokemontrades/flairhq#521]
https://github.com/azer/left-pad/issues/4

Our build will probably be broken. We should check, and update versions of things that have been fixed already (I'd imagine most have been fixed).

**Comment by not-an-aardvark** [comment]
It looks like left-pad was republished by a different author, which possibly fixes things?

**Comment by YaManicKill** [comment]
Yeah, they un-unpublished the version, so we should probably be fine. But we should run a build sometime to check.

**Comment by not-an-aardvark** [comment]
It seems like the build works fine after a fresh npm install.
