### ISSUE TITLE
FlairHQ not updated; Still displays 'Bank'

### ISSUE THREAD

**Issue by iAznFTW** [pokemontrades/flairhq#523]
When editing a trade's "Type," the dropdown menu still displays "Event" and "Bank." 

http://puu.sh/nRvMD/76c55e86b1.png

It should be updated to "Event6" and "Event3-5" (or something similar).

**Comment by YaManicKill** [comment]
Thanks, @iAznFTW that's been fixed by @not-an-aardvark and merged in now.
