### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Steav005** [pokemontrades/flairhq#544]
I often trade two (or more) times with a person in one thread:

For example:
LF 1 Eevee and 1 db f Ralts FT Many 5IV breedjects

If im adding this to my FlairHQ I face two Problems:

1. I have to use a different perma link even we traded twice within one comment string
2. I have to enter all the informations again (User, Type, Information)

If there were a way to add more trades under one permalink like a "Plus"-Button under the "Gave" and "Got" Fields so I can enter more trades

Thanks for your attention!

**Comment by not-an-aardvark** [comment]
Hello, thanks for the suggestion.

Does the "Edit" button to the right of a trade help serve this purpose? You can use it to change the "Gave"/"Got" fields on a trade.

**Comment by not-an-aardvark** [comment]
Closing this since I think the "Edit" button serves this purpose, but feel free to reopen it if I misunderstood your question.
