### ISSUE TITLE
Allow selecting gen 7 starters in flair

### ISSUE THREAD

**Issue by Raia** [pokemontrades/flairhq#549]
![Spritesheet](https://cloud.githubusercontent.com/assets/8943230/20222964/289b5db2-a7ec-11e6-80ba-993a6931d537.png)

CSS: https://gist.github.com/Raia/076c26718611ce53fabcb0e4df9fb14a

We'll probably want to be able to disable this sometime too.

**Comment by YaManicKill** [comment]
Disabling === reverting the commit :-P

**Comment by Raia** [comment]
That works, I wasn't sure if we would prefer to leave it in as a configurable thing or just do that :p

**Comment by YaManicKill** [comment]
It's probably not worth it, tbh. Any future thing we do we would have to
add the css and images anyway, and the code would be nearly identical so
easy to just reapply again. Not worth the effort to make it configurable.
But I can have a think about if there would he a useful configuration
(like, just for hiding the extra section for example).
