### ISSUE TITLE
Add gen 7 games to flair text setting

### ISSUE THREAD

**Issue by YaManicKill** [pokemontrades/flairhq#550]
So, we just need 2 more options for the game.

Should they be "S" and "M" or "Su" and "Mo" or "Sn" and "Mn" or even "Sun" and "Moon"? I was thinking just "S" and "M".

Also, I guess we should probably think about whether we'll be removing gen 6 games from the flair at some point? Obviously, we'll keep them for just now. I guess maybe the time to remove them would be when gen 6 trading goes down?

**Comment by TheSonAlsoRises** [comment]
I would also pick "S" and "M". We should keep the X/Y/OR/AS options for as long as gen6 trading works.
