### ISSUE TITLE
Update bans for tsv6 and tsv7 threads

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#554]
If we want the ban feature to work with the new [tsv6] and [tsv7] threads, FAPP will have to be updated.

**Comment by YaManicKill** [comment]
What's this?

**Comment by Raia** [comment]
Banning a user should automatically remove their TSV threads, but we recently changed the tags for gen 7.

**Comment by YaManicKill** [comment]
Ah, righty.

**Comment by not-an-aardvark** [comment]
I think this will still work fine, because it just looks for `sv` in the flair.

**Comment by YaManicKill** [comment]
Is this an issue, or isn't it?

**Comment by Raia** [comment]
Seems like our bans have been fine, so closing for now.
