### ISSUE TITLE
Add "Gen 7 Event" category

### ISSUE THREAD

**Issue by Raia** [pokemontrades/flairhq#556]
<img width="348" src="https://cloud.githubusercontent.com/assets/8943230/20334034/e3a15576-ab6b-11e6-9219-2c05b06b3478.png">

**Comment by YaManicKill** [comment]
Should we not just remove the existing event categories and add "Event"?
The generational event categories are pretty much dead anyway.

Although, that brings up the question of what we should do with the
existing 3-5 Pokémon...

**Comment by TheSonAlsoRises** [comment]
I assume traders would want to categorize their trades, and I would prefer to keep the generations separate for now.

**Comment by YaManicKill** [comment]
The problem is that adding a new category is more than just adding it in the dropdown. I never made it nice and easy to add a new category. There are quite a few areas to do it in.

**Comment by YaManicKill** [comment]
> Then if it proves too complex, just rename "Gen 6 event" to either "Gen 6/7 event" or "Event" and we will discuss the case of Bank trades later.

It's not complex, just time consuming and I don't think I'd have time before friday to do a whole new category.

Plus, I think that's not great having a whole new category. I'm happy with changing it to "Event" and keeping the bank category for just now.

Happy with that?

**Comment by TheSonAlsoRises** [comment]
Fine by me.
