### ISSUE TITLE
Unable to add trades

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#564]
As per:

* https://www.reddit.com/message/messages/6yridu
* https://www.reddit.com/message/messages/6yrmg4
* https://www.reddit.com/message/messages/6ys4sc

New trades cannot be added to FAPP, as they result in an error:

http://i.imgur.com/OEtebk0.png

**Comment by YaManicKill** [comment]
Database was full. I've compacted it which has bought us some time, but we need to migrate to our server, like we did with porybox.
