### ISSUE TITLE
"(-1 Pokémon given, 0 eggs given)"

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#576]
https://hq.porygon.co/u/Santiago1041

![bvpq3ix](https://cloud.githubusercontent.com/assets/8591366/24084691/4339cf9c-0cef-11e7-96cf-4701121f7b50.png)

**Comment by not-an-aardvark** [comment]
Is the bug that people are able to enter a negative number?

**Comment by TheSonAlsoRises** [comment]
I am unsure how we got it, but the number of Pokémon given away should be zero or positive.
