### ISSUE TITLE
Filter notifications for alts of 0000-0000-0000

### ISSUE THREAD

**Issue by Kirzi** [pokemontrades/flairhq#587]
If someone sets the invalid flair of 0000-0000-0000, it now turns up several matches for everyone else who set that very common flair. So it's kind of spammy.

1111-1111-1111 would probably be another one worth adding to this.

**Comment by YaManicKill** [comment]
This should probably be implemented as a blacklist of flairs to ignore, so that we can add existing ones through config only if we need to (it might be nice to actually have this as a UI for mods, but a config option would be the first step)

**Comment by YaManicKill** [comment]
I'll try and take a look at this, if I have time. If I don't get it done, I'll unassign myself.

**Comment by robdy** [comment]
Fixed in #623
