### ISSUE TITLE
Greasekit -> Tampermonkey

### ISSUE THREAD

**Issue by TheSonAlsoRises** [pokemontrades/flairhq#590]
From /u/BrayVoid:

>Hey, on [FlairHQ's tools page](https://hq.porygon.co/tools) it states that you should install Greasekit if you're using Safari, however Greasekit is no longer available.
However, it is now possible to get [Tampermonkey for Safari](http://tampermonkey.net/?ext=dhdg&browser=safari) so it'd be cool if you could update that page :)

**Comment by robertdyjas** [comment]
My first pull request ever, hope I did everything correctly ;)
