### ISSUE TITLE
Cannot approve trades on Firefox

### ISSUE THREAD

**Issue by robdy** [pokemontrades/flairhq#618]
When I open user profile on FHQ using Firefox, it doesn't give me checkmarks to approve the trade:
https://i.imgur.com/CxUbF7H.png

As @SnowPhoenix found, it's caused by `-moz-appearance: none` attribute in `input[type="checkbox"]:not(.search-check)`.

**Comment by pkmnbumba** [comment]
https://github.com/pokemontrades/flairhq/blob/1b63a8392671ae47e6ec22ad272ac839c65d4834/assets/styles/importer.less#L91

Changing this to `-moz-appearance: checkbox` should fix the issue.

**Comment by Raia** [comment]
Fixed in #657
