### ISSUE TITLE
Add tags/releases

### ISSUE THREAD

**Issue by robdy** [pokemontrades/flairhq#633]
It's rather minor but I think would be good to add some tags to the commits so we have release history and then start doinh the same for new releases (+changelog).

I can prepare simple script to add tags in bulk.

**Comment by McInkay** [comment]
[We used to tag releases](https://files.yamanickill.com/YC2223eh.png)

**Comment by robdy** [comment]
Yep but there are only 3 so we can start doing it again :)

**Comment by McInkay** [comment]
Yeah, I was just doing a "in my day" thing :-P

**Comment by robdy** [comment]
^^

**Comment by robdy** [comment]
Ok I have tags added to my fork, someone with access can push them and we can start tagging and writing changelog for future releases.

**Comment by Raia** [comment]
@robdy You have write access here as well :)

**Comment by robdy** [comment]
Done. Added all the tags and description for last release.
