### ISSUE TITLE
change request: tradebacks should be tracked like giveaways for number traded back

### ISSUE THREAD

**Issue by Chaos3120** [pokemontrades/flairhq#662]
helping dex completion is very slow for the reward a lot of times, incentivising users to ignore large posts or not help as much as they could, but giveaways track by number of given mons, not 'want to trade?' requests like everything else. Some tradeback dex completions can be extremely long. I personally just did an hour of tradebacks to one guy, 31 mons, and it counts as a single trade for the helper flair. Kinda a bummer :P

**Comment by Raia** [comment]
Hi!

Since this relates to /r/pokemontrades' mod policy more than FlairHQ itself, I'll redirect you to /r/pokemontrades' modmail. If you have any feedback about the flair ladder on the sub, please contact the mods here: https://www.reddit.com/message/compose?to=%2Fr%2Fpokemontrades
