### ISSUE TITLE
Virtual console trade user flairs (feature I would like to see)

### ISSUE THREAD

**Issue by AlMondNutz** [pokemontrades/flairhq#700]
As the virtual console Pokémon games have been released and are available to trade over wifi, so I think it should have a flair for the virtual console games (red, blue, yellow etc) 

If you hadn’t already noticed this is my first time using GitHub

**Comment by Dengar66** [comment]
There is no legitimate way to trade over WiFi on the VC games. The only trading they allow is over local wireless.

As such, I am closing this issue.
