### ISSUE TITLE
Trade deletion queue?

### ISSUE THREAD

**Issue by NotRaia** [pokemontrades/flairhq#74]
After actually using the site more, I think it would be useful to have a trade deletion queue of sorts.

Basically when a user lists things that shouldn't count, I want to delete the things but I also want to show the user what they did wrong. It would be cool if I could queue them for deletion and have them highlighted in red (perhaps only to mods and the user?), then deleted at a set time or something.

**Comment by YaManicKill** [comment]
Is this still wanted, or do you think it's unnecessary now? Quite low priority, but no point in keeping it in if you don't think we'll actually want it.

**Comment by TheSonAlsoRises** [comment]
I think we have managed fine without it, and as far as I know there is little to no demand for such a feature.

**Comment by YaManicKill** [comment]
Ok, I'll close for now. We can look at reopening in the future if we finish everything else.
